apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ApplicationSet
      name: eodhp
    patch: |-
      - op: replace
        path: /spec/generators/0/git/directories/0
        value: apps/*/envs/dev
      - op: replace
        path: /spec/generators/0/git/revision
        value: feature/EODHP-92-create-kubernetes-cluster-for-test-environment
      - op: replace
        path: /spec/template/spec/source/targetRevision
        value: feature/EODHP-92-create-kubernetes-cluster-for-test-environment
