apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: v1
kind: Service
metadata:
  name: eodhp-web-presence-service
  namespace: web
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: eodhp-web-presence
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: web
spec:
  clusterIP: None
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: eodhp-web-presence-database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: web
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: file-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eodhp-web-presence
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eodhp-web-presence
  template:
    metadata:
      labels:
        app: eodhp-web-presence
    spec:
      containers:
      - env:
        - name: APP_URL
          value: dev.eodhp.eco-ke-staging.com
        - name: SQL_HOST
          value: postgres-service
        - name: SQL_PORT
          value: "5432"
        - name: SQL_DATABASE
          value: web_presence_db
        - name: SQL_ENGINE
          value: django.db.backends.postgresql_psycopg2
        - name: SQL_USER
          value: admin
        - name: SQL_PASSWORD
          value: password
        - name: RESOURCE_CATALOGUE_VERSION
          value: v1.2.3
        image: public.ecr.aws/n1b3o1k2/eodhp-web-presence:0.1.0
        name: eodhp-web-presence
        ports:
        - containerPort: 8000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eodhp-web-presence-database
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eodhp-web-presence-database
  template:
    metadata:
      labels:
        app: eodhp-web-presence-database
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: web_presence_db
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: password
        image: postgres:latest
        name: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgres
          name: postgres-persistent-storage
  volumeClaimTemplates:
  - metadata:
      name: postgres-persistent-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: file-storage
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: web
spec:
  backoffLimit: 10
  template:
    spec:
      containers:
      - command:
        - sh
        - -c
        - python manage.py migrate
        env:
        - name: SQL_HOST
          value: postgres-service
        - name: SQL_PORT
          value: "5432"
        - name: SQL_DATABASE
          value: web_presence_db
        - name: SQL_ENGINE
          value: django.db.backends.postgresql_psycopg2
        - name: SQL_USER
          value: admin
        - name: SQL_PASSWORD
          value: password
        image: public.ecr.aws/n1b3o1k2/eodhp-web-presence:0.1.0
        name: db-migrate
      restartPolicy: OnFailure
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: web-presence
  namespace: web
spec:
  data:
  - remoteRef:
      key: eodhp-dev
      property: web-presence.sql_password
    secretKey: web-presence.sql_password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: web-presence
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
  name: eodhp-web-presence-ingress
  namespace: web
spec:
  ingressClassName: nginx
  rules:
  - host: dev.eodhp.eco-ke-staging.com
    http:
      paths:
      - backend:
          service:
            name: eodhp-web-presence-service
            port:
              number: 8000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - dev.eodhp.eco-ke-staging.com
    secretName: lets-encrypt
