apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: web-presence
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: web-presence
  data:
    - secretKey: web-presence.sql_password
      remoteRef:
        key: eodhp-dev
        property: "web-presence.sql_password"
---
apiVersion: v1
kind: Secret
metadata:
  name: k8s.dev.eodatahub.org.uk-tls
  annotations:
    replicator.v1.mittwald.de/replicate-from: cert-manager/k8s.dev.eodatahub.org.uk-tls
type: kubernetes.io/tls
data:
  tls.key: ""
  tls.crt: ""
