app_url: k8s.dev.eodatahub.org.uk
image: public.ecr.aws/n1b3o1k2/eodhp-web-presence:0.1.3

database:
  sql_user: "admin"
  sql_password: "password"

ingress:
  host: k8s.dev.eodatahub.org.uk

eox_viewserver:
  url: https://k8s.dev.eodatahub.org.uk/vs

stac_browser:
  url: https://k8s.dev.eodatahub.org.uk/stac/v3.1.1

storage_class: block-storage
