app_url: dev.eodhp.eco-ke-staging.com

database:
  sql_user: "admin"
  sql_password: "password"

ingress:
  host: dev.eodhp.eco-ke-staging.com

eox_viewserver:
  url: http://vs.dev.eodhp.eco-ke-staging.com/

stac_browser:
  url: http://stac.dev.eodhp.eco-ke-staging.com/

storage_class: block-storage
