apiVersion: batch/v1
kind: Job
metadata:
  name: ingest-catalogue-supported-data
spec:
  template:
    spec:
      serviceAccountName: resource-catalogue
      automountServiceAccountToken: true
      containers:
        - name: ingest-catalogue-supported-data
          image: public.ecr.aws/n1b3o1k2/config-scanning:0.1.1
          command:
            [
              "python3",
              "-m",
              "configscanning.comparefiles",
              "/tmp/catalogue-supported-data/github.com/UKEODHP/catalogue-supported-data/",
              "catalogue-data",
              "catalogue-data/supported",
            ]
          volumeMounts:
            - mountPath: /tmp
              name: temporary-storage
      initContainers:
        - name: harvest-catalogue-supported-data
          image: public.ecr.aws/n1b3o1k2/config-scanning:0.1.1
          command:
            - "/bin/sh"
            - "-c"
            - |  
              mkdir -p /tmp/catalogue-supported-data && python3 -m configscanning.repoupdater https://github.com/UKEODHP/catalogue-supported-data /tmp/catalogue-supported-data --app-id-from app-id --app-private-key-from app-private-key --pull
              python3 -m configscanning.repoupdater https://github.com/UKEODHP/catalogue-supported-data /tmp/catalogue-supported-data --app-id-from app-id --app-private-key-from app-private-key --pull
          env:
            - name: app-id-file
              value: "app-id"
            - name: app-private-key-file
              value: "app-private-key"
          volumeMounts:
            - name: github-creds
              readOnly: true
              mountPath: "/etc/github-creds"
            - mountPath: /tmp
              name: temporary-storage
      volumes:
        - name: github-creds
          secret:
            secretName: github-creds
        - name: temporary-storage
          emptyDir: {}
      restartPolicy: Never
  backoffLimit: 4
