apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-creds
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: github-creds
  data:
    - secretKey: app-id
      remoteRef:
        key: eodhp-dev
        property: resource-catalogue.github-app-id
    - secretKey: app-private-key
      remoteRef:
        key: eodhp-dev
        property: resource-catalogue.github-app-private-key
