apiVersion: v1
kind: Secret
metadata:
  name: k8s.dev.eodatahub.org.uk-tls
  annotations:
    replicator.v1.mittwald.de/replicate-from: cert-manager/eodhp-tls
type: kubernetes.io/tls
data:
  tls.key: ""
  tls.crt: ""
