apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web

resources:
  - namespace.yaml

helmCharts:
  - name: eodhp-web-presence
    repo: oci://public.ecr.aws/n1b3o1k2/helm
    releaseName: web-presence
    version: 0.1.0
    valuesFile: values.yaml
