apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-hub

resources:
  - namespace.yaml

#helmCharts:
#  - name: vs
#    repo: https://charts-public.hub.eox.at/
#    releaseName: eoxvs
#    version: 4.3.0
#    valuesFile: values.yaml