apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: eodhp
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/UKEODHP/eodhp-argocd-deployment.git
        revision: INJECT_REVISION
        directories:
          - path: "INJECT_PATH"
          - path: "apps/argocd"
            exclude: true
  template:
    metadata:
      name: "{{path[1]}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/UKEODHP/eodhp-argocd-deployment.git
        targetRevision: INJECT_REVISION
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - allowEmpty=true
