apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::312280911266:role/ResourceCatalogue-eodhp-dev-9ylvhv4X
  name: resource-catalogue
  namespace: rc
