apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fast-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "fast-api-test.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stac-fast-api-service
                port:
                  number: 8080
