apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: eodhp
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/UKEODHP/eodhp-argocd-deployment.git
        revision: bugfix/EODHP-156-automate-efs-file-system-id-in-argo-cd
        directories:
          - path: "apps/*"
          - path: "apps/argocd"
            exclude: true
  template:
    metadata:
      name: "{{path.basenameNormalized}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/UKEODHP/eodhp-argocd-deployment.git
        targetRevision: bugfix/EODHP-156-automate-efs-file-system-id-in-argo-cd
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basenameNormalized}}"
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - allowEmpty=true
