apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/UKEODHP/eodhp-argocd-deployment.git
    targetRevision: git checkout -b EODHP-169-swap-aws-alb-controller-for-nginx-ingress-controller
    path: apps/argocd
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
