apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eox

resources:
  - namespace.yaml
  - redis-pvc.yaml

helmCharts:
  - name: vs
    repo: https://charts-public.hub.eox.at/
    releaseName: eoxvs
    version: 4.3.0
    valuesFile: values.yaml

patches:
  - target:
      kind: Ingress
    path: ingress.patch.yaml
  - target:
      kind: Ingress
      name: eoxvs-*
    path: pathtype.patch.yaml
