apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - ../../base
  - secrets.yaml

helmCharts:
  - name: keycloak
    repo: oci://registry-1.docker.io/bitnamicharts/
    releaseName: keycloak
    version: 17.3.6
    valuesFile: "values.yaml"
    namespace: keycloak
