apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak
  data:
    - secretKey: password
      remoteRef:
        key: eodhp-dev
        property: keycloak.auth.adminPassword
    - secretKey: postgres-password
      remoteRef:
        key: eodhp-dev
        property: keycloak.auth.postgresPassword
