global.storageClass: block-storage
auth:
  adminUser: admin
  existingSecret: keycloak
  passwordSecretKey: password
postgresql:
  auth:
    database: keycloak
    username: keycloak
    existingSecret: keycloak
ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.dev.eodatahub.org.uk
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
  tls: true
proxy: edge
keycloakConfigCli:
  enabled: true
  configuration:
    eodhp: |
      {
        "realm": "eodhp",
        "displayName": "UK EO DataHub Platform",
        "enabled": true,
        "registrationAllowed": false,
        "registrationEmailAsUsername": false,
        "rememberMe": false,
        "verifyEmail": false,
        "loginWithEmailAllowed": true,
        "duplicateEmailsAllowed": false,
        "resetPasswordAllowed": false,
        "editUsernameAllowed": false,
        "permanentLockout": false,
        "requiredCredentials": [
          "password"
        ],
        "clients": [
          {
            "clientId": "application-hub",
            "name": "Application Hub",
            "enabled": true,
            "alwaysDisplayInConsole": true,
            "clientAuthenticatorType": "client-secret",
            "redirectUris": [
              "https://apphub.dev.eodatahub.org.uk/*"
            ],
            "webOrigins": [
              "https://apphub.dev.eodatahub.org.uk"
            ],
            "standardFlowEnabled": true,
            "implicitFlowEnabled": false,
            "publicClient": false,
            "protocol": "openid-connect",
          }
        ]
      }
