global.storageClass: block-storage
httpRelativePath: /keycloak/
auth:
  adminUser: admin
  existingSecret: keycloak
  passwordSecretKey: password
postgresql:
  auth:
    database: keycloak
    username: keycloak
    existingSecret: keycloak
ingress:
  enabled: true
  ingressClassName: nginx
  hostname: dev.eodatahub.org.uk
  tls: true
proxy: edge
keycloakConfigCli:
  enabled: true
  configuration:
    eodhp: |
      {
        "realm": "eodhp",
        "displayName": "UK EO DataHub Platform",
        "enabled": true,
        "registrationAllowed": false,
        "registrationEmailAsUsername": false,
        "rememberMe": false,
        "verifyEmail": false,
        "loginWithEmailAllowed": true,
        "duplicateEmailsAllowed": false,
        "resetPasswordAllowed": false,
        "editUsernameAllowed": false,
        "permanentLockout": false,
        "requiredCredentials": [
          "password"
        ],
        "identityProviders": [
          {
            "alias": "github",
            "providerId": "github",
            "enabled": true,
            "updateProfileFirstLoginMode": "on",
            "trustEmail": false,
            "storeToken": false,
            "addReadTokenRoleOnCreate": false,
            "authenticateByDefault": false,
            "linkOnly": false,
            "firstBrokerLoginFlowAlias": "first broker login",
            "config": {
              "clientSecret": "**********",
              "clientId": "c83f1231b8cdce667e8c"
            }
          }
        ],
        "clients": [
          {
            "clientId": "application-hub",
            "name": "Application Hub",
            "enabled": true,
            "alwaysDisplayInConsole": true,
            "clientAuthenticatorType": "client-secret",
            "redirectUris": [
              "https://dev.eodatahub.org.uk/apphub/*"
            ],
            "webOrigins": [
              "https://dev.eodatahub.org.uk/apphub"
            ],
            "standardFlowEnabled": true,
            "implicitFlowEnabled": false,
            "publicClient": false,
            "protocol": "openid-connect",
          }
        ]
      }
