global.storageClass: block-storage
auth:
  adminUser: admin
  existingSecret: keycloak
  passwordSecretKey: password
postgresql:
  auth:
    database: keycloak
    username: keycloak
    existingSecret: keycloak
ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.steg.eodhp.eco-ke-staging.com
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
  tls: true
proxy: edge
