apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proc

resources:
  - ../../base
  - secrets.yaml

helmCharts:
  - name: application-hub
    repo: https://eoepca.github.io/helm-charts/
    releaseName: app-hub
    version: 2.0.59
    valuesFile: values.yaml
    namespace: proc

generators:
 - eodhp-config.yaml

patches:
  - target:
      kind: Ingress
    patch: |-
      # Update resource catalogue to use spec.ingressClassName instead of annotation
      # "kubernetes.io/ingress.class"
      - op: remove
        path: /metadata/annotations/kubernetes.io~1ingress.class
      - op: add
        path: /spec/ingressClassName
        value: nginx
      - op: remove
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
  - target:
      kind: PodDisruptionBudget
    patch: |-
      - op: replace
        path: /apiVersion
        value: policy/v1
  - target:
      kind: Ingress
      name: app-hub-application-hub-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: application-hub-proxy-public
