apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-hub

resources:
  - ../../base

helmCharts:
  - name: application-hub
    repo: https://eoepca.github.io/helm-charts/
    releaseName: app-hub
    version: 2.0.55
    valuesFile: values.yaml
