apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proc

resources:
  - ../../base
  - secrets.yaml

helmCharts:
  - name: application-hub
    repo: https://eoepca.github.io/helm-charts/
    releaseName: app-hub
    version: 2.0.55
    valuesFile: values.yaml
    namespace: proc

patches:
  - target:
      kind: Ingress
    patch: |-
      # Update resource catalogue to use spec.ingressClassName instead of annotation
      # "kubernetes.io/ingress.class"
      - op: remove
        path: /metadata/annotations/kubernetes.io~1ingress.class
      - op: add
        path: /spec/ingressClassName
        value: nginx
  - target:
      kind: PodDisruptionBudget
    patch: |-
      - op: replace
        path: /apiVersion
        value: policy/v1
