apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-hub
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: app-hub
  data:
    - secretKey: JUPYTERHUB_CRYPT_KEY
      remoteRef:
        key: eodhp-dev
        property: "app-hub.JUPYTERHUB_CRYPT_KEY"
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: eodhp-dev
        property: "app-hub.OAUTH_CLIENT_SECRET"
---
apiVersion: v1
kind: Secret
metadata:
  name: k8s.dev.eodatahub.org.uk-tls
  annotations:
    replicator.v1.mittwald.de/replicate-from: cert-manager/eodhp-tls
type: kubernetes.io/tls
data:
  tls.key: ""
  tls.crt: ""
