ingress:
  ingressClassName: nginx
  enabled: true
  annotations: {}
  hosts:
    - host: apphub.dev.eodhp.eco-ke-staging.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: apphub.dev.eodhp.eco-ke-staging.com-tls
      hosts:
        - apphub.dev.eodhp.eco-ke-staging.com
  clusterIssuer: lets-encrypt

jupyterhub:
  fullnameOverride: "application-hub"
  hub:
    existingSecret: app-hub
    extraEnv:
      JUPYTERHUB_ENV: "dev"
      JUPYTERHUB_SINGLE_USER_IMAGE: "eoepca/pde-container:1.0.3"
      OAUTH_CALLBACK_URL: https://apphub.dev.eodhp.eco-ke-staging.com/hub/oauth_callback
      OAUTH2_USERDATA_URL: https://keycloak.dev.eodhp.eco-ke-staging.com/realms/eodhp/protocol/openid-connect/userinfo
      OAUTH2_TOKEN_URL: https://keycloak.dev.eodhp.eco-ke-staging.com/realms/eodhp/protocol/openid-connect/token
      OAUTH2_AUTHORIZE_URL: https://keycloak.dev.eodhp.eco-ke-staging.com/realms/eodhp/protocol/openid-connect/auth
      OAUTH_LOGOUT_REDIRECT_URL: "https://apphub.dev.eodhp.eco-ke-staging.com"
      OAUTH2_USERNAME_KEY: "preferred_username"
      STORAGE_CLASS: block-storage
      RESOURCE_MANAGER_WORKSPACE_PREFIX: "ws"
      JUPYTERHUB_CRYPT_KEY:
        valueFrom:
          secretKeyRef:
            name: app-hub
            key: JUPYTERHUB_CRYPT_KEY
      OAUTH_CLIENT_ID: application-hub
      OAUTH_CLIENT_SECRET:
        valueFrom:
          secretKeyRef:
            name: app-hub
            key: OAUTH_CLIENT_SECRET
    db:
      pvc:
        storageClassName: block-storage

  singleuser:
    image:
      name: jupyter/minimal-notebook
      tag: "2343e33dec46"
    profileList:
      - display_name: "Minimal environment"
        description: "To avoid too much bells and whistles: Python."
        default: "True"
      - display_name: "EOEPCA profile"
        description: "Sample profile"
        kubespawner_override:
          cpu_limit": 4
          mem_limit": "8G"

nodeSelector:
  key: role
  value: general

serviceAccount:
  create: true
  annotations: {}
