apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ades
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: basic-auth
  data:
    - secretKey: ingress.annotations.auth
      remoteRef:
        key: eodhp-dev
        property: "ades.ingress.annotations.auth"
