apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ades

resources:
  - ../../base
  - secrets.yaml

helmCharts:
  - name: zoo-project-dru
    repo: https://zoo-project.github.io/charts/
    releaseName: zoo-project-dru
    version: 0.2.6
    valuesFile: values.yaml
    namespace: ades

configMapGenerator:
  - name: zoo-project-dru-zoofpm-config
    literals:
      - STAGEOUT_AWS_SERVICEURL=https://s3.eu-west-2.amazonaws.com
      - STAGEOUT_AWS_REGION=eu-west-2
      - STAGEOUT_OUTPUT=eodhp-ades-dev

patches:
  - target:
      kind: Ingress
    patch: |-
      # Update resource catalogue to use spec.ingressClassName instead of annotation
      # "kubernetes.io/ingress.class"
      - op: remove
        path: /metadata/annotations/kubernetes.io~1ingress.class
      - op: add
        path: /spec/ingressClassName
        value: nginx
  - target:
      kind: Deployment
      name: zoo-project-dru-zoofpm
    patch: |-
      # Add STAGEOUT values as environment variables
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STAGEOUT_AWS_SERVICEURL
          valueFrom:
            configMapKeyRef:
              name: zoo-project-dru-zoofpm-config
              key: STAGEOUT_AWS_SERVICEURL
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STAGEOUT_AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: zoo-project-dru-zoofpm-config
              key: STAGEOUT_AWS_REGION
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STAGEOUT_OUTPUT
          valueFrom:
            configMapKeyRef:
              name: zoo-project-dru-zoofpm-config
              key: STAGEOUT_OUTPUT
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/8
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          mountPath: /opt/zooservices_user
          name: ades-processing-services
  - target:
      kind: Deployment
      name: zoo-project-dru-zookernel
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/20
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          mountPath: /opt/zooservices_user
          name: ades-processing-services
  - target:
      kind: ServiceAccount
      name: zoo-project-dru-processing-manager
    patch: |-
      - op: add
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::312280911266:role/ADESProcessingManager-eodhp-dev-iTfh9VYd
  - target:
      kind: PersistentVolumeClaim
      #name: zoo-project-dru-processing-services
    patch: |-
      - op: add
        path: /spec/persistentVolumeReclaimPolicy
        value: Retain

  - path: delete-pvc-patch.yaml
