apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ades

resources:
  - namespace.yaml

helmCharts:
  - name: ades
    repo: https://eoepca.github.io/helm-charts
    releaseName: ades
    version: 2.0.24
    valuesFile: values.yaml

patches:
  - target:
      kind: Ingress
    patch: |-
      - op: add
        path: /spec/ingressClassName
        value: nginx
  - target:
      kind: Ingress
    patch: |-
      # Set TLS secret name
      - op: add
        path: /spec/tls/0/secretName
        value: ades.dev.eodhp.eco-ke-staging.com-tls
      - op: add
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: lets-encrypt
