apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ades

resources:
  - ../../base
  - secrets.yaml

helmCharts:
  - name: zoo-project-dru
    repo: https://zoo-project.github.io/charts/
    releaseName: zoo-project-dru
    version: 0.2.6
    valuesFile: values.yaml
    namespace: ades

configMapGenerator:
  - name: zoo-project-dru-zoofpm-config
    literals:
      - STAGEOUT_AWS_SERVICEURL=https://s3.eu-west-2.amazonaws.com
      - STAGEOUT_AWS_REGION=eu-west-2
      - STAGEOUT_OUTPUT=eodhp-ades-dev
      - STAGEOUT_AWS_ACCESS_KEY_ID=""
      - STAGEOUT_AWS_SECRET_ACCESS_KEY=""

patches:
  - target:
      kind: Ingress
    patch: |-
      # Update resource catalogue to use spec.ingressClassName instead of annotation
      # "kubernetes.io/ingress.class"
      - op: remove
        path: /metadata/annotations/kubernetes.io~1ingress.class
      - op: add
        path: /spec/ingressClassName
        value: nginx
  - target:
      kind: Deployment
      name: zoo-project-dru-zoofpm
    patch: |-
      # Add STAGEOUT secrets as environment variables
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STAGEOUT_AWS_SERVICEURL
          valueFrom:
            configMapKeyRef:
              name: zoo-project-dru-zoofpm-config
              key: STAGEOUT_AWS_SERVICEURL
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STAGEOUT_AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: zoo-project-dru-zoofpm-config
              key: STAGEOUT_AWS_REGION
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STAGEOUT_OUTPUT
          valueFrom:
            configMapKeyRef:
              name: zoo-project-dru-zoofpm-config
              key: STAGEOUT_OUTPUT
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STAGEOUT_AWS_SECRET_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: zoo-project-dru-zoofpm-config
              key: STAGEOUT_AWS_SECRET_ACCESS_KEY
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STAGEOUT_AWS_ACCESS_KEY_ID
          valueFrom:
            configMapKeyRef:
              name: zoo-project-dru-zoofpm-config
              key: STAGEOUT_AWS_ACCESS_KEY_ID
      # - op: add
      #   path: /spec/template/spec/containers/0/env/-
      #   value:
      #     name: STAGEOUT_AWS_ACCESS_KEY_ID
      #     valueFrom:
      #       secretKeyRef:
      #         name: ades-secret
      #         key: workflowExecutor.inputs.STAGEOUT_AWS_ACCESS_KEY_ID
      # - op: add
      #   path: /spec/template/spec/containers/0/env/-
      #   value:
      #     name: STAGEOUT_AWS_SECRET_ACCESS_KEY
      #     valueFrom:
      #       secretKeyRef:
      #         name: ades-secret
      #         key: workflowExecutor.inputs.STAGEOUT_AWS_SECRET_ACCESS_KEY
      - op: add
        path: /spec/template/spec/serviceAccountName
        value: zoo-project-dru
  - target:
      kind: ServiceAccount
      name: zoo-project-dru
    patch: |-
      # Configure service account manually
      - op: add
        path: /automountServiceAccountToken
        value: true
      - op: add
        path: /metadata/name
        value: default
  - path: delete-pvc-patch.yaml
