apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ades
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: ades-secret
  data:
    - secretKey: workflowExecutor.inputs.STAGEOUT_AWS_SERVICEURL
      remoteRef:
        key: eodhp-dev
        property: "ades.workflowExecutor.inputs.STAGEOUT_AWS_SERVICEURL"
    - secretKey: workflowExecutor.inputs.STAGEOUT_AWS_ACCESS_KEY_ID
      remoteRef:
        key: eodhp-dev
        property: "ades.workflowExecutor.inputs.STAGEOUT_AWS_ACCESS_KEY_ID"
    - secretKey: workflowExecutor.inputs.STAGEOUT_AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: eodhp-dev
        property: "ades.workflowExecutor.inputs.STAGEOUT_AWS_SECRET_ACCESS_KEY"
    - secretKey: workflowExecutor.inputs.STAGEOUT_AWS_REGION
      remoteRef:
        key: eodhp-dev
        property: "ades.workflowExecutor.inputs.STAGEOUT_AWS_REGION"
    - secretKey: workflowExecutor.inputs.STAGEOUT_OUTPUT
      remoteRef:
        key: eodhp-dev
        property: "ades.workflowExecutor.inputs.STAGEOUT_OUTPUT"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: basic-auth
  namespace: ades
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: basic-auth
  data:
    - secretKey: auth
      remoteRef:
        key: eodhp-dev
        property: "ades.ingress.annotations.auth"
