apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: basic-auth
  namespace: ades
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: basic-auth
  data:
    - secretKey: auth
      remoteRef:
        key: eodhp-dev
        property: "ades.ingress.annotations.auth"
