apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ades
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: ades
  data:
    - secretKey: workflowExecutor.inputs.STAGEOUT_AWS_ACCESS_KEY_ID
      remoteRef:
        key: eodhp-dev
        property: "ades.workflowExecutor.inputs.STAGEOUT_AWS_ACCESS_KEY_ID"
