apiVersion: batch/v1
kind: Job
metadata:
  name: config-scanning
spec:
  template:
    spec:
      serviceAccountName: s3-access
      volumes:
        - name: secret-volume
          secret:
            secretName: dotfile-secret
      containers:
        - name: harvest-root-catalogue-1
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
          env:
            - name: app-id-file
              value: "app-id"
            - name: app-private-key-file
              value: "app-private-key"
          image: public.ecr.aws/n1b3o1k2/config-scanning:0.0.4
          command: ["python3", "-m", "configscanning.repoupdater", "https://github.com/UKEODHP/catalogue-data/", "/tmp", "--app-id-from", "app-id", "--app-private-key-from", "app-private-key", "--pull"]

        - name: harvest-root-catalogue-2
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
          env:
            - name: app-id-file
              value: "app-id"
            - name: app-private-key-file
              value: "app-private-key"
          image: public.ecr.aws/n1b3o1k2/config-scanning:0.0.4-test3
          command: ["python3", "-m", "configscanning.repoupdater", "https://github.com/UKEODHP/catalogue-supported-data/", "/tmp", "--app-id-from", "app-id", "--app-private-key-from", "app-private-key", "--pull"]
        - name: ingest-root-catalogue-1
#          env:
#            - name: AWS_ACCESS_KEY
#              value:
#            - name: AWS_SECRET_ACCESS_KEY
#              value:
          image: public.ecr.aws/n1b3o1k2/config-scanning:0.0.4-test3
          command: ["python3", "-m", "configscanning.comparefiles", "/tmp/catalogue-data/", "catalogue-data", "", "catalogue-supported-data"]
        - name: ingest-root-catalogue-2
#          env:
#            - name: AWS_ACCESS_KEY
#              value:
#            - name: AWS_SECRET_ACCESS_KEY
#              value:
          image: public.ecr.aws/n1b3o1k2/config-scanning:0.0.4
          command: ["python3", "-m", "configscanning.comparefiles", "/tmp/catalogue-supported-data/", "catalogue-data", "", ""]
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  app-id: ODQyOTIxCg==
  app-private-key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMFRuZmhERWtoT3BsM2dLZ0VxK0pPOFc1V1UzK3kvb1RBQ2I1U3VrN2NXTEUxRFZSClZBVUVwZWVRZ2NTYWVIakkyekZqOG9FWU91OWFEMkxGYko4M1hpMTQyWkYrdVdwTS96UEZYVVJ2S2ZVaXE5OXoKRVJZSVpTMDJJOEljZFdNK2M5ODMwRU1rcGhEMGYyRmY0NlZMVHpJMzRNTVFidjhQMGZ0Skw5TFNEc1pYYVBILwpWUVRTaFdhMVg3V0t4cnkvTUQ3U0xVUW5YWVJ2TGZibFJvYzA1aUExVFA5b1FJYVlQaURSeENhU29tRlZVaS9DCmhGWG82bHVpTDRBYWVtMi9PM1NGNzhNMGxwd1F1YkRVaFpCbXUvVmFSSUd4elhvYjkxWjY3WUZYVmN3eVR2OGIKeVNEaVJGOUp3OSt5bVVRdHlKMjNMUGdYQlNWVldsK2d4TklPUVFJREFRQUJBb0lCQVFDZkdQM3hmSmtEaFdZKwo0d29zQzFVMG9ZN203TnRDNm4rR1R4eWtMU1NwZk95bFhZSGhmUXRpeU9wbTgwUnZOWkd1dENrSFg4azRENGdSClNROU5JT2t1Y1MrRGFoTE9GWnBGT1czc0ZUemV6K3cwZSs3NDRDTTBKS1FWbnVhYkVRT05nd0RqR2h1Rk9FRmoKbDMwZUV6Um9IWXpHR2k2bDZNaHo2VHhtNUU0ZE1xK05RR3dKTDV1VzhzZDNoMlZ1MTVjVWZpVWd6bVpZVjBKYwo3c1E4NkErMVhzRm5VL1QvUDJSOVhIeEladzRqKzE5UWo5aHVMT3ZHbXp4UGprRmxCbCsyM2tJYnBHT1o0R0RjClovcU9tajZmTGlxcWF4ckQ3Z0xEZXUvbld0cGE3YmEzOTZlcTN4bExYN2EvaDdUR3lMV283QkYycXg3SlhrR2QKc2s2NmVxVWRBb0dCQU9mOHY5R1MydkYzVVlEdEZKMm83aHdrMUpTWDdqVVo2QmxydzYxZzZ5TDh2OXBLd0tnRgpGOGUzbmQrYURkNTVuZWlUUzBLSmNrNzZ5Wi8rbmU5ZWFpY3dieWdmaFpuSVY1VVc3YjlzbUdRYnpqSnd2dEV2CmtzZEdGRDVSOHAzU2RjTTRaRzMrZncvdG1iNHAwTThhL3FZeGZ1OWd4aGdlYVpXS2lnRTdTcGlUQW9HQkFPYmgKL2RqZUFLZisrOEpwTnBvUG04Z09UNk5qUUx3dkFOWDUxbldqdmZzZ2hPbEZaZzFUbEdYWS9aTzgwUDZHMVhCRgpIQ3RLeVpQb1Q5Qnd6Z2JUWVBSSDZoN0VwTnlBTjM0eDhmUEFKdU9RdmtFeUVseExQRjZZREZFOGRBZUhiOExMCjY5bUhyRk5xK0ZsaHRyZG55Ti9FbXEwM0c1REFsTDZWbU9SWHVDWmJBb0dCQU52NzN1R2F3cWRySUF5RHhLTGsKaURhRDdsbWg0SzdXRERQZTdzVkFQSGtHOTk3R04vNmNKYnFyTWJmUlhBbDFoZm4vZ3NScmxjdXpJUExvL1ZiNQpUdXd1ajVtYW1wUURXSm4yRGlrUmowaU8zVzhUWHI3NnY5TGJiMkxSVHFHOTZ4SGVMYzNvSVJFM25DeXBkbXFPCkRLQUlHM2hmYWptQXpWcVM3dDdRSEtLbEFvR0FIMThyeC9ENmM5bFF5aXpUcjRGWmNJaUpSN0V2MWFJcFllbk4KdXpSaGx5TG5ERzlTbTVMMHdoWUc5ckVjVU1sdmJRN204ZmI2aHU5MUVPU1RDaGhrdnl5YVlrM2ovTllyTkNtRApMOVMzTkFxeDMxZjNhTFVNWWVvVkdtQzFmMlJteWpnOU50U1psTWdmTUwzM1B0cUtUK1YrQXZWTytJOUNadGNhCjdFUURFS3NDZ1lCRWM4Tm5KR291RlpJdkRxMUpwalYwVE5hNm5HMUNhc2xvd3B5dWFESmRVK09DNnk5RXJIZVEKZi9tNFJtbTk4RXl5R3FtTHFtNGtXamlaeVpNNlJtMW5ZS25JRjN3cGk5NktSYkNSbXFVZUdRZkExcGM1SUFXQwpZUnpzV2trVmRqK3JqR3FRTTFYUVZEdk1ZUGZ5VFQvQ2krWlA5bytUUHRZZFZlcUVoYXhOdUE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
