apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd      
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.53.11
    helm:
      releaseName: argocd
  syncPolicy:
    automated:
      prune: false 
      selfHeal: true 
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true